services:
  app:
    build: .
    image: wallet-app
    container_name: wallet_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "wallet"
  db:
    image: postgres:15
    container_name: wallet_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    volumes:
      - ./postgres_db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pg_data: