services:
  app:
    build: .
    container_name: wallet_app
    depends_on:
      - db
      - test
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "wallet"
  db:
    image: postgres:15
    container_name: wallet_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    volumes:
      - ./postgres_db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  test:
    image: golang:alpine
    container_name: wallet_app_test
    command: go test ./tests/
    working_dir: /app
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "wallet"
    volumes:
      - .:/app

volumes:
  pg_data: